version: '3'

tasks:
  setup:
    cmds:
      - java -version || echo "Java not found, please install at least Java 21"
      - task: format-check

  run:
    cmds:
      - |
        if [ "$(uname)" = "Linux" ] || [ "$(uname)" = "Darwin" ]; then
          ./gradlew run
        elif [ "$OS" = "Windows_NT" ]; then
          gradlew.bat run
        else
          echo "Unsupported OS"
        fi

  build:
    sources:
      - api/**
      - shork/**
      - build.gradle.kts
      - settings.gradle.kts
      - gradle.properties
    generates:
      - api/build/libs/api-all.jar
    cmds:
      - |
        if [ "$(uname)" = "Linux" ] || [ "$(uname)" = "Darwin" ]; then
          ./gradlew buildFatJar
        elif [ "$OS" = "Windows_NT" ]; then
          gradlew.bat buildFatJar
        else
          echo "Unsupported OS"
        fi

  test:
    cmds:
      - |
        if [ "$(uname)" = "Linux" ] || [ "$(uname)" = "Darwin" ]; then
          ./gradlew check
        elif [ "$OS" = "Windows_NT" ]; then
          gradlew.bat check
        else
          echo "Unsupported OS"
        fi

  format:
    cmds:
      - |
        if [ "$(uname)" = "Linux" ] || [ "$(uname)" = "Darwin" ]; then
          ./gradlew ktfmtFormat
        elif [ "$OS" = "Windows_NT" ]; then
          gradlew.bat ktfmtFormat
        else
          echo "Unsupported OS"
        fi

  format-check:
    cmds:
      - |
        if [ "$(uname)" = "Linux" ] || [ "$(uname)" = "Darwin" ]; then
          ./gradlew ktfmtCheck
        elif [ "$OS" = "Windows_NT" ]; then
          gradlew.bat ktfmtCheck
        else
          echo "Unsupported OS"
        fi

  clean:
    cmds:
      - |
        if [ "$(uname)" = "Linux" ] || [ "$(uname)" = "Darwin" ]; then
          ./gradlew clean
        elif [ "$OS" = "Windows_NT" ]; then
          gradlew.bat clean
        else
          echo "Unsupported OS"
        fi

