###
POST http://localhost:8080/api/v1/lobby
Content-Type: application/json

{
  "playerName": "playerA"
}

###

GET http://localhost:8080/api/v1/lobby/0/status

###

GET http://localhost:8080/api/v1/lobby/-1/status

###

GET http://localhost:8080/api/v1/lobby/0/status?showVisualizationData=true

###

GET http://localhost:8080/api/v1/lobby/0/status?showVisualizationData=false

###
# Submit code for player A, will run until the end of the game
POST http://localhost:8080/api/v1/lobby/0/code/playerA
Content-Type: application/json

{
  "code": "mov 0, 1"
}

###
# Submit code for player B, will run until the end of the game
POST http://localhost:8080/api/v1/lobby/0/code/playerB
Content-Type: application/json

{
  "code": "mov 0, 1"
}

###
GET http://localhost:8080/api/v1/lobby