import HexagonalBoard from "@/components/hexagonalBoard/HexagonalBoard.tsx";
import "./gameVisu.css";
import Header from "@/components/header/Header.tsx";
import Footer from "@/components/footer/Footer.tsx";
import { useEffect, useRef } from "react";
import { HexagonalTileProps } from "@/components/hexagonalTile/HexagonalTile.tsx";

function GameVisuPage() {
	const visuData = [
		{
			playerId: "playerA",
			programCounterBefore: 0,
			programCounterAfter: 1,
			programCountersOfOtherProcesses: [],
			memoryReads: [0, 0, 1, 0, 1, 1],
			memoryWrites: [0, 101, 1],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 101,
			programCounterAfter: 102,
			programCountersOfOtherProcesses: [],
			memoryReads: [101, 101, 102, 101, 102, 102],
			memoryWrites: [102],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 1,
			programCounterAfter: 2,
			programCountersOfOtherProcesses: [],
			memoryReads: [1, 1, 2, 1, 2, 2],
			memoryWrites: [2],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 102,
			programCounterAfter: 103,
			programCountersOfOtherProcesses: [],
			memoryReads: [102, 102, 103, 102, 103, 103],
			memoryWrites: [103],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 2,
			programCounterAfter: 3,
			programCountersOfOtherProcesses: [],
			memoryReads: [2, 2, 3, 2, 3, 3],
			memoryWrites: [3],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 103,
			programCounterAfter: 104,
			programCountersOfOtherProcesses: [],
			memoryReads: [103, 103, 104, 103, 104, 104],
			memoryWrites: [104],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 3,
			programCounterAfter: 4,
			programCountersOfOtherProcesses: [],
			memoryReads: [3, 3, 4, 3, 4, 4],
			memoryWrites: [4],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 104,
			programCounterAfter: 105,
			programCountersOfOtherProcesses: [],
			memoryReads: [104, 104, 105, 104, 105, 105],
			memoryWrites: [105],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 4,
			programCounterAfter: 5,
			programCountersOfOtherProcesses: [],
			memoryReads: [4, 4, 5, 4, 5, 5],
			memoryWrites: [5],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 105,
			programCounterAfter: 106,
			programCountersOfOtherProcesses: [],
			memoryReads: [105, 105, 106, 105, 106, 106],
			memoryWrites: [106],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 5,
			programCounterAfter: 6,
			programCountersOfOtherProcesses: [],
			memoryReads: [5, 5, 6, 5, 6, 6],
			memoryWrites: [6],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 106,
			programCounterAfter: 107,
			programCountersOfOtherProcesses: [],
			memoryReads: [106, 106, 107, 106, 107, 107],
			memoryWrites: [107],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 6,
			programCounterAfter: 7,
			programCountersOfOtherProcesses: [],
			memoryReads: [6, 6, 7, 6, 7, 7],
			memoryWrites: [7],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 107,
			programCounterAfter: 108,
			programCountersOfOtherProcesses: [],
			memoryReads: [107, 107, 108, 107, 108, 108],
			memoryWrites: [108],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 7,
			programCounterAfter: 8,
			programCountersOfOtherProcesses: [],
			memoryReads: [7, 7, 8, 7, 8, 8],
			memoryWrites: [8],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 108,
			programCounterAfter: 109,
			programCountersOfOtherProcesses: [],
			memoryReads: [108, 108, 109, 108, 109, 109],
			memoryWrites: [109],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 8,
			programCounterAfter: 9,
			programCountersOfOtherProcesses: [],
			memoryReads: [8, 8, 9, 8, 9, 9],
			memoryWrites: [9],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 109,
			programCounterAfter: 110,
			programCountersOfOtherProcesses: [],
			memoryReads: [109, 109, 110, 109, 110, 110],
			memoryWrites: [110],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 9,
			programCounterAfter: 10,
			programCountersOfOtherProcesses: [],
			memoryReads: [9, 9, 10, 9, 10, 10],
			memoryWrites: [10],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 110,
			programCounterAfter: 111,
			programCountersOfOtherProcesses: [],
			memoryReads: [110, 110, 111, 110, 111, 111],
			memoryWrites: [111],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 10,
			programCounterAfter: 11,
			programCountersOfOtherProcesses: [],
			memoryReads: [10, 10, 11, 10, 11, 11],
			memoryWrites: [11],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 111,
			programCounterAfter: 112,
			programCountersOfOtherProcesses: [],
			memoryReads: [111, 111, 112, 111, 112, 112],
			memoryWrites: [112],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 11,
			programCounterAfter: 12,
			programCountersOfOtherProcesses: [],
			memoryReads: [11, 11, 12, 11, 12, 12],
			memoryWrites: [12],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 112,
			programCounterAfter: 113,
			programCountersOfOtherProcesses: [],
			memoryReads: [112, 112, 113, 112, 113, 113],
			memoryWrites: [113],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 12,
			programCounterAfter: 13,
			programCountersOfOtherProcesses: [],
			memoryReads: [12, 12, 13, 12, 13, 13],
			memoryWrites: [13],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 113,
			programCounterAfter: 114,
			programCountersOfOtherProcesses: [],
			memoryReads: [113, 113, 114, 113, 114, 114],
			memoryWrites: [114],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 13,
			programCounterAfter: 14,
			programCountersOfOtherProcesses: [],
			memoryReads: [13, 13, 14, 13, 14, 14],
			memoryWrites: [14],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 114,
			programCounterAfter: 115,
			programCountersOfOtherProcesses: [],
			memoryReads: [114, 114, 115, 114, 115, 115],
			memoryWrites: [115],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 14,
			programCounterAfter: 15,
			programCountersOfOtherProcesses: [],
			memoryReads: [14, 14, 15, 14, 15, 15],
			memoryWrites: [15],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 115,
			programCounterAfter: 116,
			programCountersOfOtherProcesses: [],
			memoryReads: [115, 115, 116, 115, 116, 116],
			memoryWrites: [116],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 15,
			programCounterAfter: 16,
			programCountersOfOtherProcesses: [],
			memoryReads: [15, 15, 16, 15, 16, 16],
			memoryWrites: [16],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 116,
			programCounterAfter: 117,
			programCountersOfOtherProcesses: [],
			memoryReads: [116, 116, 117, 116, 117, 117],
			memoryWrites: [117],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 16,
			programCounterAfter: 17,
			programCountersOfOtherProcesses: [],
			memoryReads: [16, 16, 17, 16, 17, 17],
			memoryWrites: [17],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 117,
			programCounterAfter: 118,
			programCountersOfOtherProcesses: [],
			memoryReads: [117, 117, 118, 117, 118, 118],
			memoryWrites: [118],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 17,
			programCounterAfter: 18,
			programCountersOfOtherProcesses: [],
			memoryReads: [17, 17, 18, 17, 18, 18],
			memoryWrites: [18],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 118,
			programCounterAfter: 119,
			programCountersOfOtherProcesses: [],
			memoryReads: [118, 118, 119, 118, 119, 119],
			memoryWrites: [119],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 18,
			programCounterAfter: 19,
			programCountersOfOtherProcesses: [],
			memoryReads: [18, 18, 19, 18, 19, 19],
			memoryWrites: [19],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 119,
			programCounterAfter: 120,
			programCountersOfOtherProcesses: [],
			memoryReads: [119, 119, 120, 119, 120, 120],
			memoryWrites: [120],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 19,
			programCounterAfter: 20,
			programCountersOfOtherProcesses: [],
			memoryReads: [19, 19, 20, 19, 20, 20],
			memoryWrites: [20],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 120,
			programCounterAfter: 121,
			programCountersOfOtherProcesses: [],
			memoryReads: [120, 120, 121, 120, 121, 121],
			memoryWrites: [121],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 20,
			programCounterAfter: 21,
			programCountersOfOtherProcesses: [],
			memoryReads: [20, 20, 21, 20, 21, 21],
			memoryWrites: [21],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 121,
			programCounterAfter: 122,
			programCountersOfOtherProcesses: [],
			memoryReads: [121, 121, 122, 121, 122, 122],
			memoryWrites: [122],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 21,
			programCounterAfter: 22,
			programCountersOfOtherProcesses: [],
			memoryReads: [21, 21, 22, 21, 22, 22],
			memoryWrites: [22],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 122,
			programCounterAfter: 123,
			programCountersOfOtherProcesses: [],
			memoryReads: [122, 122, 123, 122, 123, 123],
			memoryWrites: [123],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 22,
			programCounterAfter: 23,
			programCountersOfOtherProcesses: [],
			memoryReads: [22, 22, 23, 22, 23, 23],
			memoryWrites: [23],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 123,
			programCounterAfter: 124,
			programCountersOfOtherProcesses: [],
			memoryReads: [123, 123, 124, 123, 124, 124],
			memoryWrites: [124],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 23,
			programCounterAfter: 24,
			programCountersOfOtherProcesses: [],
			memoryReads: [23, 23, 24, 23, 24, 24],
			memoryWrites: [24],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 124,
			programCounterAfter: 125,
			programCountersOfOtherProcesses: [],
			memoryReads: [124, 124, 125, 124, 125, 125],
			memoryWrites: [125],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 24,
			programCounterAfter: 25,
			programCountersOfOtherProcesses: [],
			memoryReads: [24, 24, 25, 24, 25, 25],
			memoryWrites: [25],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 125,
			programCounterAfter: 126,
			programCountersOfOtherProcesses: [],
			memoryReads: [125, 125, 126, 125, 126, 126],
			memoryWrites: [126],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 25,
			programCounterAfter: 26,
			programCountersOfOtherProcesses: [],
			memoryReads: [25, 25, 26, 25, 26, 26],
			memoryWrites: [26],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 126,
			programCounterAfter: 127,
			programCountersOfOtherProcesses: [],
			memoryReads: [126, 126, 127, 126, 127, 127],
			memoryWrites: [127],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 26,
			programCounterAfter: 27,
			programCountersOfOtherProcesses: [],
			memoryReads: [26, 26, 27, 26, 27, 27],
			memoryWrites: [27],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 127,
			programCounterAfter: 128,
			programCountersOfOtherProcesses: [],
			memoryReads: [127, 127, 128, 127, 128, 128],
			memoryWrites: [128],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 27,
			programCounterAfter: 28,
			programCountersOfOtherProcesses: [],
			memoryReads: [27, 27, 28, 27, 28, 28],
			memoryWrites: [28],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 128,
			programCounterAfter: 129,
			programCountersOfOtherProcesses: [],
			memoryReads: [128, 128, 129, 128, 129, 129],
			memoryWrites: [129],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 28,
			programCounterAfter: 29,
			programCountersOfOtherProcesses: [],
			memoryReads: [28, 28, 29, 28, 29, 29],
			memoryWrites: [29],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 129,
			programCounterAfter: 130,
			programCountersOfOtherProcesses: [],
			memoryReads: [129, 129, 130, 129, 130, 130],
			memoryWrites: [130],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 29,
			programCounterAfter: 30,
			programCountersOfOtherProcesses: [],
			memoryReads: [29, 29, 30, 29, 30, 30],
			memoryWrites: [30],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 130,
			programCounterAfter: 131,
			programCountersOfOtherProcesses: [],
			memoryReads: [130, 130, 131, 130, 131, 131],
			memoryWrites: [131],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 30,
			programCounterAfter: 31,
			programCountersOfOtherProcesses: [],
			memoryReads: [30, 30, 31, 30, 31, 31],
			memoryWrites: [31],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 131,
			programCounterAfter: 132,
			programCountersOfOtherProcesses: [],
			memoryReads: [131, 131, 132, 131, 132, 132],
			memoryWrites: [132],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 31,
			programCounterAfter: 32,
			programCountersOfOtherProcesses: [],
			memoryReads: [31, 31, 32, 31, 32, 32],
			memoryWrites: [32],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 132,
			programCounterAfter: 133,
			programCountersOfOtherProcesses: [],
			memoryReads: [132, 132, 133, 132, 133, 133],
			memoryWrites: [133],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 32,
			programCounterAfter: 33,
			programCountersOfOtherProcesses: [],
			memoryReads: [32, 32, 33, 32, 33, 33],
			memoryWrites: [33],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 133,
			programCounterAfter: 134,
			programCountersOfOtherProcesses: [],
			memoryReads: [133, 133, 134, 133, 134, 134],
			memoryWrites: [134],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 33,
			programCounterAfter: 34,
			programCountersOfOtherProcesses: [],
			memoryReads: [33, 33, 34, 33, 34, 34],
			memoryWrites: [34],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 134,
			programCounterAfter: 135,
			programCountersOfOtherProcesses: [],
			memoryReads: [134, 134, 135, 134, 135, 135],
			memoryWrites: [135],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 34,
			programCounterAfter: 35,
			programCountersOfOtherProcesses: [],
			memoryReads: [34, 34, 35, 34, 35, 35],
			memoryWrites: [35],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 135,
			programCounterAfter: 136,
			programCountersOfOtherProcesses: [],
			memoryReads: [135, 135, 136, 135, 136, 136],
			memoryWrites: [136],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 35,
			programCounterAfter: 36,
			programCountersOfOtherProcesses: [],
			memoryReads: [35, 35, 36, 35, 36, 36],
			memoryWrites: [36],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 136,
			programCounterAfter: 137,
			programCountersOfOtherProcesses: [],
			memoryReads: [136, 136, 137, 136, 137, 137],
			memoryWrites: [137],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 36,
			programCounterAfter: 37,
			programCountersOfOtherProcesses: [],
			memoryReads: [36, 36, 37, 36, 37, 37],
			memoryWrites: [37],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 137,
			programCounterAfter: 138,
			programCountersOfOtherProcesses: [],
			memoryReads: [137, 137, 138, 137, 138, 138],
			memoryWrites: [138],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 37,
			programCounterAfter: 38,
			programCountersOfOtherProcesses: [],
			memoryReads: [37, 37, 38, 37, 38, 38],
			memoryWrites: [38],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 138,
			programCounterAfter: 139,
			programCountersOfOtherProcesses: [],
			memoryReads: [138, 138, 139, 138, 139, 139],
			memoryWrites: [139],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 38,
			programCounterAfter: 39,
			programCountersOfOtherProcesses: [],
			memoryReads: [38, 38, 39, 38, 39, 39],
			memoryWrites: [39],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 139,
			programCounterAfter: 140,
			programCountersOfOtherProcesses: [],
			memoryReads: [139, 139, 140, 139, 140, 140],
			memoryWrites: [140],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 39,
			programCounterAfter: 40,
			programCountersOfOtherProcesses: [],
			memoryReads: [39, 39, 40, 39, 40, 40],
			memoryWrites: [40],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 140,
			programCounterAfter: 141,
			programCountersOfOtherProcesses: [],
			memoryReads: [140, 140, 141, 140, 141, 141],
			memoryWrites: [141],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 40,
			programCounterAfter: 41,
			programCountersOfOtherProcesses: [],
			memoryReads: [40, 40, 41, 40, 41, 41],
			memoryWrites: [41],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 141,
			programCounterAfter: 142,
			programCountersOfOtherProcesses: [],
			memoryReads: [141, 141, 142, 141, 142, 142],
			memoryWrites: [142],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 41,
			programCounterAfter: 42,
			programCountersOfOtherProcesses: [],
			memoryReads: [41, 41, 42, 41, 42, 42],
			memoryWrites: [42],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 142,
			programCounterAfter: 143,
			programCountersOfOtherProcesses: [],
			memoryReads: [142, 142, 143, 142, 143, 143],
			memoryWrites: [143],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 42,
			programCounterAfter: 43,
			programCountersOfOtherProcesses: [],
			memoryReads: [42, 42, 43, 42, 43, 43],
			memoryWrites: [43],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 143,
			programCounterAfter: 144,
			programCountersOfOtherProcesses: [],
			memoryReads: [143, 143, 144, 143, 144, 144],
			memoryWrites: [144],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 43,
			programCounterAfter: 44,
			programCountersOfOtherProcesses: [],
			memoryReads: [43, 43, 44, 43, 44, 44],
			memoryWrites: [44],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 144,
			programCounterAfter: 145,
			programCountersOfOtherProcesses: [],
			memoryReads: [144, 144, 145, 144, 145, 145],
			memoryWrites: [145],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 44,
			programCounterAfter: 45,
			programCountersOfOtherProcesses: [],
			memoryReads: [44, 44, 45, 44, 45, 45],
			memoryWrites: [45],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 145,
			programCounterAfter: 146,
			programCountersOfOtherProcesses: [],
			memoryReads: [145, 145, 146, 145, 146, 146],
			memoryWrites: [146],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 45,
			programCounterAfter: 46,
			programCountersOfOtherProcesses: [],
			memoryReads: [45, 45, 46, 45, 46, 46],
			memoryWrites: [46],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 146,
			programCounterAfter: 147,
			programCountersOfOtherProcesses: [],
			memoryReads: [146, 146, 147, 146, 147, 147],
			memoryWrites: [147],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 46,
			programCounterAfter: 47,
			programCountersOfOtherProcesses: [],
			memoryReads: [46, 46, 47, 46, 47, 47],
			memoryWrites: [47],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 147,
			programCounterAfter: 148,
			programCountersOfOtherProcesses: [],
			memoryReads: [147, 147, 148, 147, 148, 148],
			memoryWrites: [148],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 47,
			programCounterAfter: 48,
			programCountersOfOtherProcesses: [],
			memoryReads: [47, 47, 48, 47, 48, 48],
			memoryWrites: [48],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 148,
			programCounterAfter: 149,
			programCountersOfOtherProcesses: [],
			memoryReads: [148, 148, 149, 148, 149, 149],
			memoryWrites: [149],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 48,
			programCounterAfter: 49,
			programCountersOfOtherProcesses: [],
			memoryReads: [48, 48, 49, 48, 49, 49],
			memoryWrites: [49],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 149,
			programCounterAfter: 150,
			programCountersOfOtherProcesses: [],
			memoryReads: [149, 149, 150, 149, 150, 150],
			memoryWrites: [150],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 49,
			programCounterAfter: 50,
			programCountersOfOtherProcesses: [],
			memoryReads: [49, 49, 50, 49, 50, 50],
			memoryWrites: [50],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 150,
			programCounterAfter: 151,
			programCountersOfOtherProcesses: [],
			memoryReads: [150, 150, 151, 150, 151, 151],
			memoryWrites: [151],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 50,
			programCounterAfter: 51,
			programCountersOfOtherProcesses: [],
			memoryReads: [50, 50, 51, 50, 51, 51],
			memoryWrites: [51],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 151,
			programCounterAfter: 152,
			programCountersOfOtherProcesses: [],
			memoryReads: [151, 151, 152, 151, 152, 152],
			memoryWrites: [152],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 51,
			programCounterAfter: 52,
			programCountersOfOtherProcesses: [],
			memoryReads: [51, 51, 52, 51, 52, 52],
			memoryWrites: [52],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 152,
			programCounterAfter: 153,
			programCountersOfOtherProcesses: [],
			memoryReads: [152, 152, 153, 152, 153, 153],
			memoryWrites: [153],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 52,
			programCounterAfter: 53,
			programCountersOfOtherProcesses: [],
			memoryReads: [52, 52, 53, 52, 53, 53],
			memoryWrites: [53],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 153,
			programCounterAfter: 154,
			programCountersOfOtherProcesses: [],
			memoryReads: [153, 153, 154, 153, 154, 154],
			memoryWrites: [154],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 53,
			programCounterAfter: 54,
			programCountersOfOtherProcesses: [],
			memoryReads: [53, 53, 54, 53, 54, 54],
			memoryWrites: [54],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 154,
			programCounterAfter: 155,
			programCountersOfOtherProcesses: [],
			memoryReads: [154, 154, 155, 154, 155, 155],
			memoryWrites: [155],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 54,
			programCounterAfter: 55,
			programCountersOfOtherProcesses: [],
			memoryReads: [54, 54, 55, 54, 55, 55],
			memoryWrites: [55],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 155,
			programCounterAfter: 156,
			programCountersOfOtherProcesses: [],
			memoryReads: [155, 155, 156, 155, 156, 156],
			memoryWrites: [156],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 55,
			programCounterAfter: 56,
			programCountersOfOtherProcesses: [],
			memoryReads: [55, 55, 56, 55, 56, 56],
			memoryWrites: [56],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 156,
			programCounterAfter: 157,
			programCountersOfOtherProcesses: [],
			memoryReads: [156, 156, 157, 156, 157, 157],
			memoryWrites: [157],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 56,
			programCounterAfter: 57,
			programCountersOfOtherProcesses: [],
			memoryReads: [56, 56, 57, 56, 57, 57],
			memoryWrites: [57],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 157,
			programCounterAfter: 158,
			programCountersOfOtherProcesses: [],
			memoryReads: [157, 157, 158, 157, 158, 158],
			memoryWrites: [158],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 57,
			programCounterAfter: 58,
			programCountersOfOtherProcesses: [],
			memoryReads: [57, 57, 58, 57, 58, 58],
			memoryWrites: [58],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 158,
			programCounterAfter: 159,
			programCountersOfOtherProcesses: [],
			memoryReads: [158, 158, 159, 158, 159, 159],
			memoryWrites: [159],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 58,
			programCounterAfter: 59,
			programCountersOfOtherProcesses: [],
			memoryReads: [58, 58, 59, 58, 59, 59],
			memoryWrites: [59],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 159,
			programCounterAfter: 160,
			programCountersOfOtherProcesses: [],
			memoryReads: [159, 159, 160, 159, 160, 160],
			memoryWrites: [160],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 59,
			programCounterAfter: 60,
			programCountersOfOtherProcesses: [],
			memoryReads: [59, 59, 60, 59, 60, 60],
			memoryWrites: [60],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 160,
			programCounterAfter: 161,
			programCountersOfOtherProcesses: [],
			memoryReads: [160, 160, 161, 160, 161, 161],
			memoryWrites: [161],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 60,
			programCounterAfter: 61,
			programCountersOfOtherProcesses: [],
			memoryReads: [60, 60, 61, 60, 61, 61],
			memoryWrites: [61],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 161,
			programCounterAfter: 162,
			programCountersOfOtherProcesses: [],
			memoryReads: [161, 161, 162, 161, 162, 162],
			memoryWrites: [162],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 61,
			programCounterAfter: 62,
			programCountersOfOtherProcesses: [],
			memoryReads: [61, 61, 62, 61, 62, 62],
			memoryWrites: [62],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 162,
			programCounterAfter: 163,
			programCountersOfOtherProcesses: [],
			memoryReads: [162, 162, 163, 162, 163, 163],
			memoryWrites: [163],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 62,
			programCounterAfter: 63,
			programCountersOfOtherProcesses: [],
			memoryReads: [62, 62, 63, 62, 63, 63],
			memoryWrites: [63],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 163,
			programCounterAfter: 164,
			programCountersOfOtherProcesses: [],
			memoryReads: [163, 163, 164, 163, 164, 164],
			memoryWrites: [164],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 63,
			programCounterAfter: 64,
			programCountersOfOtherProcesses: [],
			memoryReads: [63, 63, 64, 63, 64, 64],
			memoryWrites: [64],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 164,
			programCounterAfter: 165,
			programCountersOfOtherProcesses: [],
			memoryReads: [164, 164, 165, 164, 165, 165],
			memoryWrites: [165],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 64,
			programCounterAfter: 65,
			programCountersOfOtherProcesses: [],
			memoryReads: [64, 64, 65, 64, 65, 65],
			memoryWrites: [65],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 165,
			programCounterAfter: 166,
			programCountersOfOtherProcesses: [],
			memoryReads: [165, 165, 166, 165, 166, 166],
			memoryWrites: [166],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 65,
			programCounterAfter: 66,
			programCountersOfOtherProcesses: [],
			memoryReads: [65, 65, 66, 65, 66, 66],
			memoryWrites: [66],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 166,
			programCounterAfter: 167,
			programCountersOfOtherProcesses: [],
			memoryReads: [166, 166, 167, 166, 167, 167],
			memoryWrites: [167],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 66,
			programCounterAfter: 67,
			programCountersOfOtherProcesses: [],
			memoryReads: [66, 66, 67, 66, 67, 67],
			memoryWrites: [67],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 167,
			programCounterAfter: 168,
			programCountersOfOtherProcesses: [],
			memoryReads: [167, 167, 168, 167, 168, 168],
			memoryWrites: [168],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 67,
			programCounterAfter: 68,
			programCountersOfOtherProcesses: [],
			memoryReads: [67, 67, 68, 67, 68, 68],
			memoryWrites: [68],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 168,
			programCounterAfter: 169,
			programCountersOfOtherProcesses: [],
			memoryReads: [168, 168, 169, 168, 169, 169],
			memoryWrites: [169],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 68,
			programCounterAfter: 69,
			programCountersOfOtherProcesses: [],
			memoryReads: [68, 68, 69, 68, 69, 69],
			memoryWrites: [69],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 169,
			programCounterAfter: 170,
			programCountersOfOtherProcesses: [],
			memoryReads: [169, 169, 170, 169, 170, 170],
			memoryWrites: [170],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 69,
			programCounterAfter: 70,
			programCountersOfOtherProcesses: [],
			memoryReads: [69, 69, 70, 69, 70, 70],
			memoryWrites: [70],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 170,
			programCounterAfter: 171,
			programCountersOfOtherProcesses: [],
			memoryReads: [170, 170, 171, 170, 171, 171],
			memoryWrites: [171],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 70,
			programCounterAfter: 71,
			programCountersOfOtherProcesses: [],
			memoryReads: [70, 70, 71, 70, 71, 71],
			memoryWrites: [71],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 171,
			programCounterAfter: 172,
			programCountersOfOtherProcesses: [],
			memoryReads: [171, 171, 172, 171, 172, 172],
			memoryWrites: [172],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 71,
			programCounterAfter: 72,
			programCountersOfOtherProcesses: [],
			memoryReads: [71, 71, 72, 71, 72, 72],
			memoryWrites: [72],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 172,
			programCounterAfter: 173,
			programCountersOfOtherProcesses: [],
			memoryReads: [172, 172, 173, 172, 173, 173],
			memoryWrites: [173],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 72,
			programCounterAfter: 73,
			programCountersOfOtherProcesses: [],
			memoryReads: [72, 72, 73, 72, 73, 73],
			memoryWrites: [73],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 173,
			programCounterAfter: 174,
			programCountersOfOtherProcesses: [],
			memoryReads: [173, 173, 174, 173, 174, 174],
			memoryWrites: [174],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 73,
			programCounterAfter: 74,
			programCountersOfOtherProcesses: [],
			memoryReads: [73, 73, 74, 73, 74, 74],
			memoryWrites: [74],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 174,
			programCounterAfter: 175,
			programCountersOfOtherProcesses: [],
			memoryReads: [174, 174, 175, 174, 175, 175],
			memoryWrites: [175],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 74,
			programCounterAfter: 75,
			programCountersOfOtherProcesses: [],
			memoryReads: [74, 74, 75, 74, 75, 75],
			memoryWrites: [75],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 175,
			programCounterAfter: 176,
			programCountersOfOtherProcesses: [],
			memoryReads: [175, 175, 176, 175, 176, 176],
			memoryWrites: [176],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 75,
			programCounterAfter: 76,
			programCountersOfOtherProcesses: [],
			memoryReads: [75, 75, 76, 75, 76, 76],
			memoryWrites: [76],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 176,
			programCounterAfter: 177,
			programCountersOfOtherProcesses: [],
			memoryReads: [176, 176, 177, 176, 177, 177],
			memoryWrites: [177],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 76,
			programCounterAfter: 77,
			programCountersOfOtherProcesses: [],
			memoryReads: [76, 76, 77, 76, 77, 77],
			memoryWrites: [77],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 177,
			programCounterAfter: 178,
			programCountersOfOtherProcesses: [],
			memoryReads: [177, 177, 178, 177, 178, 178],
			memoryWrites: [178],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 77,
			programCounterAfter: 78,
			programCountersOfOtherProcesses: [],
			memoryReads: [77, 77, 78, 77, 78, 78],
			memoryWrites: [78],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 178,
			programCounterAfter: 179,
			programCountersOfOtherProcesses: [],
			memoryReads: [178, 178, 179, 178, 179, 179],
			memoryWrites: [179],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 78,
			programCounterAfter: 79,
			programCountersOfOtherProcesses: [],
			memoryReads: [78, 78, 79, 78, 79, 79],
			memoryWrites: [79],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 179,
			programCounterAfter: 180,
			programCountersOfOtherProcesses: [],
			memoryReads: [179, 179, 180, 179, 180, 180],
			memoryWrites: [180],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 79,
			programCounterAfter: 80,
			programCountersOfOtherProcesses: [],
			memoryReads: [79, 79, 80, 79, 80, 80],
			memoryWrites: [80],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 180,
			programCounterAfter: 181,
			programCountersOfOtherProcesses: [],
			memoryReads: [180, 180, 181, 180, 181, 181],
			memoryWrites: [181],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 80,
			programCounterAfter: 81,
			programCountersOfOtherProcesses: [],
			memoryReads: [80, 80, 81, 80, 81, 81],
			memoryWrites: [81],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 181,
			programCounterAfter: 182,
			programCountersOfOtherProcesses: [],
			memoryReads: [181, 181, 182, 181, 182, 182],
			memoryWrites: [182],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 81,
			programCounterAfter: 82,
			programCountersOfOtherProcesses: [],
			memoryReads: [81, 81, 82, 81, 82, 82],
			memoryWrites: [82],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 182,
			programCounterAfter: 183,
			programCountersOfOtherProcesses: [],
			memoryReads: [182, 182, 183, 182, 183, 183],
			memoryWrites: [183],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 82,
			programCounterAfter: 83,
			programCountersOfOtherProcesses: [],
			memoryReads: [82, 82, 83, 82, 83, 83],
			memoryWrites: [83],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 183,
			programCounterAfter: 184,
			programCountersOfOtherProcesses: [],
			memoryReads: [183, 183, 184, 183, 184, 184],
			memoryWrites: [184],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 83,
			programCounterAfter: 84,
			programCountersOfOtherProcesses: [],
			memoryReads: [83, 83, 84, 83, 84, 84],
			memoryWrites: [84],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 184,
			programCounterAfter: 185,
			programCountersOfOtherProcesses: [],
			memoryReads: [184, 184, 185, 184, 185, 185],
			memoryWrites: [185],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 84,
			programCounterAfter: 85,
			programCountersOfOtherProcesses: [],
			memoryReads: [84, 84, 85, 84, 85, 85],
			memoryWrites: [85],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 185,
			programCounterAfter: 186,
			programCountersOfOtherProcesses: [],
			memoryReads: [185, 185, 186, 185, 186, 186],
			memoryWrites: [186],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 85,
			programCounterAfter: 86,
			programCountersOfOtherProcesses: [],
			memoryReads: [85, 85, 86, 85, 86, 86],
			memoryWrites: [86],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 186,
			programCounterAfter: 187,
			programCountersOfOtherProcesses: [],
			memoryReads: [186, 186, 187, 186, 187, 187],
			memoryWrites: [187],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 86,
			programCounterAfter: 87,
			programCountersOfOtherProcesses: [],
			memoryReads: [86, 86, 87, 86, 87, 87],
			memoryWrites: [87],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 187,
			programCounterAfter: 188,
			programCountersOfOtherProcesses: [],
			memoryReads: [187, 187, 188, 187, 188, 188],
			memoryWrites: [188],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 87,
			programCounterAfter: 88,
			programCountersOfOtherProcesses: [],
			memoryReads: [87, 87, 88, 87, 88, 88],
			memoryWrites: [88],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 188,
			programCounterAfter: 189,
			programCountersOfOtherProcesses: [],
			memoryReads: [188, 188, 189, 188, 189, 189],
			memoryWrites: [189],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 88,
			programCounterAfter: 89,
			programCountersOfOtherProcesses: [],
			memoryReads: [88, 88, 89, 88, 89, 89],
			memoryWrites: [89],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 189,
			programCounterAfter: 190,
			programCountersOfOtherProcesses: [],
			memoryReads: [189, 189, 190, 189, 190, 190],
			memoryWrites: [190],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 89,
			programCounterAfter: 90,
			programCountersOfOtherProcesses: [],
			memoryReads: [89, 89, 90, 89, 90, 90],
			memoryWrites: [90],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 190,
			programCounterAfter: 191,
			programCountersOfOtherProcesses: [],
			memoryReads: [190, 190, 191, 190, 191, 191],
			memoryWrites: [191],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 90,
			programCounterAfter: 91,
			programCountersOfOtherProcesses: [],
			memoryReads: [90, 90, 91, 90, 91, 91],
			memoryWrites: [91],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 191,
			programCounterAfter: 192,
			programCountersOfOtherProcesses: [],
			memoryReads: [191, 191, 192, 191, 192, 192],
			memoryWrites: [192],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 91,
			programCounterAfter: 92,
			programCountersOfOtherProcesses: [],
			memoryReads: [91, 91, 92, 91, 92, 92],
			memoryWrites: [92],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 192,
			programCounterAfter: 193,
			programCountersOfOtherProcesses: [],
			memoryReads: [192, 192, 193, 192, 193, 193],
			memoryWrites: [193],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 92,
			programCounterAfter: 93,
			programCountersOfOtherProcesses: [],
			memoryReads: [92, 92, 93, 92, 93, 93],
			memoryWrites: [93],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 193,
			programCounterAfter: 194,
			programCountersOfOtherProcesses: [],
			memoryReads: [193, 193, 194, 193, 194, 194],
			memoryWrites: [194],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 93,
			programCounterAfter: 94,
			programCountersOfOtherProcesses: [],
			memoryReads: [93, 93, 94, 93, 94, 94],
			memoryWrites: [94],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 194,
			programCounterAfter: 195,
			programCountersOfOtherProcesses: [],
			memoryReads: [194, 194, 195, 194, 195, 195],
			memoryWrites: [195],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 94,
			programCounterAfter: 95,
			programCountersOfOtherProcesses: [],
			memoryReads: [94, 94, 95, 94, 95, 95],
			memoryWrites: [95],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 195,
			programCounterAfter: 196,
			programCountersOfOtherProcesses: [],
			memoryReads: [195, 195, 196, 195, 196, 196],
			memoryWrites: [196],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 95,
			programCounterAfter: 96,
			programCountersOfOtherProcesses: [],
			memoryReads: [95, 95, 96, 95, 96, 96],
			memoryWrites: [96],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 196,
			programCounterAfter: 197,
			programCountersOfOtherProcesses: [],
			memoryReads: [196, 196, 197, 196, 197, 197],
			memoryWrites: [197],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 96,
			programCounterAfter: 97,
			programCountersOfOtherProcesses: [],
			memoryReads: [96, 96, 97, 96, 97, 97],
			memoryWrites: [97],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 197,
			programCounterAfter: 198,
			programCountersOfOtherProcesses: [],
			memoryReads: [197, 197, 198, 197, 198, 198],
			memoryWrites: [198],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 97,
			programCounterAfter: 98,
			programCountersOfOtherProcesses: [],
			memoryReads: [97, 97, 98, 97, 98, 98],
			memoryWrites: [98],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 198,
			programCounterAfter: 199,
			programCountersOfOtherProcesses: [],
			memoryReads: [198, 198, 199, 198, 199, 199],
			memoryWrites: [199],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 98,
			programCounterAfter: 99,
			programCountersOfOtherProcesses: [],
			memoryReads: [98, 98, 99, 98, 99, 99],
			memoryWrites: [99],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 199,
			programCounterAfter: 200,
			programCountersOfOtherProcesses: [],
			memoryReads: [199, 199, 200, 199, 200, 200],
			memoryWrites: [200],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 99,
			programCounterAfter: 100,
			programCountersOfOtherProcesses: [],
			memoryReads: [99, 99, 100, 99, 100, 100],
			memoryWrites: [100],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 200,
			programCounterAfter: 201,
			programCountersOfOtherProcesses: [],
			memoryReads: [200, 200, 201, 200, 201, 201],
			memoryWrites: [201],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 100,
			programCounterAfter: 101,
			programCountersOfOtherProcesses: [],
			memoryReads: [100, 100, 101, 100, 101, 101],
			memoryWrites: [101],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 201,
			programCounterAfter: 202,
			programCountersOfOtherProcesses: [],
			memoryReads: [201, 201, 202, 201, 202, 202],
			memoryWrites: [202],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 101,
			programCounterAfter: 102,
			programCountersOfOtherProcesses: [],
			memoryReads: [101, 101, 102, 101, 102, 102],
			memoryWrites: [102],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 202,
			programCounterAfter: 203,
			programCountersOfOtherProcesses: [],
			memoryReads: [202, 202, 203, 202, 203, 203],
			memoryWrites: [203],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 102,
			programCounterAfter: 103,
			programCountersOfOtherProcesses: [],
			memoryReads: [102, 102, 103, 102, 103, 103],
			memoryWrites: [103],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 203,
			programCounterAfter: 204,
			programCountersOfOtherProcesses: [],
			memoryReads: [203, 203, 204, 203, 204, 204],
			memoryWrites: [204],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 103,
			programCounterAfter: 104,
			programCountersOfOtherProcesses: [],
			memoryReads: [103, 103, 104, 103, 104, 104],
			memoryWrites: [104],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 204,
			programCounterAfter: 205,
			programCountersOfOtherProcesses: [],
			memoryReads: [204, 204, 205, 204, 205, 205],
			memoryWrites: [205],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 104,
			programCounterAfter: 105,
			programCountersOfOtherProcesses: [],
			memoryReads: [104, 104, 105, 104, 105, 105],
			memoryWrites: [105],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 205,
			programCounterAfter: 206,
			programCountersOfOtherProcesses: [],
			memoryReads: [205, 205, 206, 205, 206, 206],
			memoryWrites: [206],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 105,
			programCounterAfter: 106,
			programCountersOfOtherProcesses: [],
			memoryReads: [105, 105, 106, 105, 106, 106],
			memoryWrites: [106],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 206,
			programCounterAfter: 207,
			programCountersOfOtherProcesses: [],
			memoryReads: [206, 206, 207, 206, 207, 207],
			memoryWrites: [207],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 106,
			programCounterAfter: 107,
			programCountersOfOtherProcesses: [],
			memoryReads: [106, 106, 107, 106, 107, 107],
			memoryWrites: [107],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 207,
			programCounterAfter: 208,
			programCountersOfOtherProcesses: [],
			memoryReads: [207, 207, 208, 207, 208, 208],
			memoryWrites: [208],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 107,
			programCounterAfter: 108,
			programCountersOfOtherProcesses: [],
			memoryReads: [107, 107, 108, 107, 108, 108],
			memoryWrites: [108],
			processDied: false,
		},
		{
			playerId: "playerB",
			programCounterBefore: 208,
			programCounterAfter: 209,
			programCountersOfOtherProcesses: [],
			memoryReads: [208, 208, 209, 208, 209, 209],
			memoryWrites: [209],
			processDied: false,
		},
		{
			playerId: "playerA",
			programCounterBefore: 108,
			programCounterAfter: 109,
			programCountersOfOtherProcesses: [],
			memoryReads: [108, 108, 109, 108, 109, 109],
			memoryWrites: [109],
			processDied: false,
		},
	];

	const interval_time: number = 33;
	const counterRef = useRef(0);

	useEffect(() => {
		const interval = setInterval(() => {
			if (counterRef.current >= visuData.length) {
				console.log("Done visualizing!");
				clearInterval(interval);
				return;
			}
			const currentIteration = visuData[counterRef.current];
			// console.log(currentIteration);
			for (const writeIndex of currentIteration.memoryWrites) {
				const color =
					currentIteration.playerId == "playerA" ? "#FF006E" : "#00FFFF";
				if (boardRef.current == null) {
					return;
				}
				boardRef.current.updateTile(
					Math.floor(writeIndex / 128),
					writeIndex % 128,
					{ fill: color },
				);
			}
			counterRef.current++;
		}, interval_time);

		// Clear interval on component unmount
		return () => clearInterval(interval);
	}, []);

	const boardRef = useRef<{
		updateTile: (
			row: number,
			col: number,
			props: Partial<HexagonalTileProps>,
		) => void;
	}>(null);

	return (
		<div id={"everything"}>
			<Header />
			<div id={"boardBuffer"} />
			<div id={"visuBoard"}>
				<HexagonalBoard
					rows={64}
					tilesPerRow={128}
					ref={boardRef}
				></HexagonalBoard>
			</div>
			<Footer />
		</div>
	);
}

export default GameVisuPage;
