name: "Backend"
on:
  push:
    paths:
        - 'backend/**'
        - 'e2e/**'
        - '.github/workflows/backend.yml'

jobs:
  kt-lint-backend:
    name: "Lint- and Format-Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Lint- and Format-Check
        working-directory: backend/
        run: ./gradlew ktfmtCheck

  kt-unittest-backend:
    name: "Unit Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 23, 21 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Tests
        working-directory: backend/
        run: ./gradlew test
