name: "Build and Test"
on:
  push:

jobs:
  e2e-tests:
    name: "Run E2E playwright tests"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      working-directory: e2e
      run: npm ci

    - name: Install Playwright Browsers
      working-directory: e2e
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: e2e
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  build-frontend:
    name: "Build and Test Frontend"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      working-directory: frontend/app
      run: | 
          npm ci
          npm install @microsoft/eslint-formatter-sarif@3.1.0

    - name: Run Prettier
      working-directory: frontend/app
      run: npx prettier --check src

    - name: Run ESLint
      env:
        SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
      working-directory: frontend/app
      run: npx eslint src
        --format @microsoft/eslint-formatter-sarif
        --output-file eslint-results.sarif

    - name: Build project
      working-directory: frontend/app
      run: npm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          frontend/app/dist

    - name: Run unit tests
      working-directory: frontend/app
      run: npm test

  build-backend:
    name: "Unit Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Format Check, Tests and Build
        working-directory: backend/
        run: ./gradlew clean ktfmtCheck test build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-jar
          path: backend/api/build/libs/api-all.jar
