name: Branch or Tag Deleted
on: delete

jobs:
  delete:
    if: github.event.ref_type == 'branch' || github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"
          curl -X DELETE https://corewar-deployment.schnelle.dev/deployments/${{ github.event.ref }} -H "Authorization: Bearer ${{ secrets.DEPLOYMENT_TOKEN }}"

      - name: Clean up ghcr image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          IMAGE_ID=$(gh api /orgs/corewar-teamprojekt/packages/container/aio/versions --paginate -q ".[] | select(.metadata.container.tags | index(\"${{ github.event.ref }}\")) | .id")
          gh api --method DELETE /orgs/corewar-teamprojekt/packages/container/aio/versions/$IMAGE_ID
