name: "Frontend: Lint and Format"

on:
  push:
  pull_request:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        working-directory: frontend/app
        run: |
          npm install
          npm install @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run Prettier
        working-directory: frontend/app
        run: npx prettier --check src

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        working-directory: frontend/app
        run: npx eslint src
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: frontend/app/eslint-results.sarif
          wait-for-processing: true

