name: Unassign Idle Issues

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # This schedules the job to run once a day (midnight UTC)

jobs:
  unassign_idle_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      uses: cli/gh-actions@v2
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install jq bash -y

    - name: Unassign Idle Issues
      env:
        ASSIGNMENT_TIMEOUT_HOURS: ${{ env.ASSIGNMENT_TIMEOUT_HOURS || 72 }} # Default of 72 hours
      run: |
        TIMEOUT=$((60*60*ASSIGNMENT_TIMEOUT_HOURS)) # Secs/Min * Mins/Hour * Assigner Timeout Hours
        echo "Unassigning issues that have been idle for more than $ASSIGNMENT_TIMEOUT_HOURS hours"

        # Get the list of issues that match the criteria
        issues=$(gh issue list --json "projectItems,updatedAt,assignees,url,labels" \
        -q ".[] | select (.assignees | length > 0) | select((now - (.updatedAt | fromdateiso8601)) > $TIMEOUT) | if(.projectItems | all(.status.name == \"Todo\")) then . else empty end")

        echo "Unassigning the following issues:"
        echo $issues | jq -r ".jql"
        echo "Executing the following commands:"

        commands=$(echo $issues | jq -r ".url as \$url | .assignees[] | \"gh issue edit \(\$url) --remove-assignee \(.login)\"")
        echo $commands

        echo $commands | xargs -n 1 bash -c

